services:
  postgres:
    image: postgres:16-alpine
    container_name: ufo_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ufo_user
      POSTGRES_PASSWORD: ufo_password
      POSTGRES_DB: ufo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
